services:
  php-app:
    build: .
    container_name: php-app
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql-db 
      DB_NAME: my_friend_system
      DB_USER: myuser
      DB_PASS: mypassword
    depends_on:
      mysql:
        condition: service_healthy  # Ensures MySQL is ready before starting PHP

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2611
      MYSQL_DATABASE: my_friend_system  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: mypassword  
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  
